[package]
name="todo-rust-cli"
version ="0.1.0"
edition="2021"

[dependencies]
clap = { version = "4.5.27", features = ["cargo"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
